### ISSUE TITLE
Successfull payment redirection problem

### ISSUE THREAD

**Issue by g666nz** [totaljs/eshop#38]
Hi, 
So i've been able to succesfully integrate a new theme around eshop. However when I do my payment, it successfully takes the payment and when being redirected it goes back to the checkout page and not the checkout-detail page showing confirmation of the payment. Do you know where i could have gone wrong??

**Comment by petersirka** [comment]
Hi @g666nz,
sorry for delay. Did you change `/sitemap` file?

- Payment processing https://github.com/totaljs/eshop/blob/master/controllers/eshop.js#L192
- Payment URL https://github.com/totaljs/eshop/blob/master/sitemap#L10

__Processing:__
- PayPal evaluates URL: `/checkout/ORDER_ID/paypal/`
- if the payment is proccessed then Eshop redirects the user back `../` otherwise shows `checkout-error` view.
