### ISSUE TITLE
Alternatives to memory database

### ISSUE THREAD

**Issue by anddimario** [totaljs/eshop#48]
Hi, is there the possibility to use a mysql or mongodb database? Are there some docs or have you some suggestions about that?

**Comment by petersirka** [comment]
Hi @anddimario,
here is older version which supports MongoDB and PostgreSQL: <https://github.com/totaljs/eshop/releases/tag/v5.0.0>

**Comment by petersirka** [comment]
BTW: NoSQL embedded is not memory database (you can disabled it, just remove `definitions/datanase.js` file), it's embedded DB.

**Comment by anddimario** [comment]
Thanks @petersirka, so the newest versions use json file stored in databases/, are there some possibility to use a database, maybe with https://github.com/totaljs/node-sqlagent ? Is there some reasons you use this instead a standard db?

**Comment by petersirka** [comment]
__so the newest versions use json file stored in `databases/`__:
Not quite because NoSQL embedded creates not valid JSON file.

__are there some possibility to use a database__:
No, you need to rewrite all DB operations in the source-code manually.

__Is there some reasons you use this instead a standard db?__
What is standard DB? Embedded database has more benefits than RDBMS/MognoDB. You don't need any installation, any DB driver, etc. (just copy the source-code between servers and the Eshop will work correcly). NoSQL embedded can handle less than 20 000 products and that's enough.

---

I din't continue with 3 versions of Eshop (embededd, MongoDB, PostgreSQL) because there was a lot of work and that was unpiad work.

**Comment by anddimario** [comment]
I understand you points :)
Really thanks for your projects and for your response.
