### ISSUE TITLE
Does eshop support i18n ? how to add language ?

### ISSUE THREAD

**Issue by goodforever** [totaljs/eshop#55]
Does eshop support i18n ? how to add language ?

**Comment by petersirka** [comment]
Hi,
eshop supports localization. It's a bit complicated because you can localize text, not products ... Eshop uses Total.js localization mechanism, read here:

- <https://docs.totaljs.com/latest/en.html#pages~Localization>
- try example https://github.com/totaljs/examples/tree/master/localization-resources
